# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the static HTML file to the Nginx public directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
